language: python
dist: xenial
sudo: true
python:
  - 3.4
  - 3.5
  - 3.6
  - 3.7
install:
  - pip install -e ".[tests]"
script: flake8 --isort-show-traceback && py.test
notifications:
  slack: ivelum:BK5tmHAiON50wnqsamRLXaw0
